// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZachHairStudio.Shared.Db;

#nullable disable

namespace ZachHairStudio.Shared.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Appointments.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StatusChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Appointments.AppointmentSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SlotStart")
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("StylistId", "SlotStart")
                        .IsUnique();

                    b.ToTable("AppointmentSlots");
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Availability.StylistTimeOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StylistTimeOff");
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Availability.StylistWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("StylistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StylistWorkingHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 4,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 5,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 6,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 4,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 5,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 6,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 3
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 3
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 4,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 3
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 5,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 3
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 6,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 3
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 4
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 4
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 4,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 4
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = 5,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 4
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = 6,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 4
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = 0,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 1
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = 0,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 24,
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 2
                        },
                        new
                        {
                            Id = 25,
                            DayOfWeek = 0,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 3
                        },
                        new
                        {
                            Id = 26,
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 3
                        },
                        new
                        {
                            Id = 27,
                            DayOfWeek = 0,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 4
                        },
                        new
                        {
                            Id = 28,
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(18, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            StylistId = 4
                        });
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Services.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cuts",
                            DisplayOrder = 1,
                            DurationMinutes = 45,
                            ImageUrl = "/uploads/services/precision-cut.jpg",
                            IsActive = true,
                            LongDescription = "A tailored cut shaped around your face, texture, and daily styling routine. Includes a consultation and finishing touches so your hair leaves polished and easy to maintain.",
                            Name = "Precision Cut",
                            Price = 35m,
                            ShortDescription = "Tailored haircuts designed to complement your face shape and lifestyle perfectly.",
                            Slug = "precision-cut"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Color",
                            DisplayOrder = 2,
                            DurationMinutes = 90,
                            ImageUrl = "/uploads/services/color-and-highlights.jpg",
                            IsActive = true,
                            LongDescription = "Dimensional color and highlight work customized to your skin tone, cut, and maintenance goals. The service uses premium products for glossy color, soft grow-out, and a salon-fresh finish.",
                            Name = "Color & Highlights",
                            Price = 80m,
                            ShortDescription = "Vibrant color treatments and natural-looking highlights using premium products.",
                            Slug = "color-and-highlights"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Styling",
                            DisplayOrder = 3,
                            DurationMinutes = 45,
                            ImageUrl = "/uploads/services/blowout-and-styling.jpg",
                            IsActive = true,
                            LongDescription = "A smooth professional blowout or styled finish tailored to the occasion, from everyday polish to event-ready volume. Ideal when you want shine, movement, and a finished look without a full cut or color service.",
                            Name = "Blowout & Styling",
                            Price = 55m,
                            ShortDescription = "Professional blowouts and styling for any occasion — weddings, events, or everyday glam.",
                            Slug = "blowout-and-styling"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Treatments",
                            DisplayOrder = 4,
                            DurationMinutes = 120,
                            ImageUrl = "/uploads/services/keratin-treatment.jpg",
                            IsActive = true,
                            LongDescription = "A smoothing treatment designed to reduce frizz, increase shine, and make daily styling easier. Best for clients looking for a longer-lasting sleek finish and improved manageability between salon visits.",
                            Name = "Keratin Treatment",
                            Price = 120m,
                            ShortDescription = "Smoothing treatments that eliminate frizz and add lasting shine and manageability.",
                            Slug = "keratin-treatment"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Treatments",
                            DisplayOrder = 5,
                            DurationMinutes = 40,
                            ImageUrl = "/uploads/services/scalp-treatment.jpg",
                            IsActive = true,
                            LongDescription = "A restorative scalp-focused service that refreshes, hydrates, and supports a healthier hair environment. Recommended for clients wanting comfort, balance, and a relaxing reset between larger services.",
                            Name = "Scalp Treatment",
                            Price = 65m,
                            ShortDescription = "Revitalizing scalp therapies to promote health, hydration, and hair growth.",
                            Slug = "scalp-treatment"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Styling",
                            DisplayOrder = 6,
                            DurationMinutes = 210,
                            ImageUrl = "/uploads/services/full-glam-package.jpg",
                            IsActive = true,
                            LongDescription = "The full studio transformation package combining a precision cut, color service, blowout, and scalp treatment. Built for clients who want the complete Zach Hair Studio experience in one coordinated visit.",
                            Name = "Full Glam Package",
                            Price = 199m,
                            ShortDescription = "Cut + Color + Blowout + Scalp treatment. The complete studio experience in one visit.",
                            Slug = "full-glam-package"
                        });
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Stylists.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Zin Min",
                            Slug = "zin-min"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "May Yoon",
                            Slug = "may-yoon"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Thiri Cho",
                            Slug = "thiri-cho"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Sai Min Htet",
                            Slug = "sai-min-htet"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ZachHairStudio.Shared.Features.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ZachHairStudio.Shared.Features.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZachHairStudio.Shared.Features.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ZachHairStudio.Shared.Features.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Appointments.AppointmentSlot", b =>
                {
                    b.HasOne("ZachHairStudio.Shared.Features.Appointments.Appointment", "Appointment")
                        .WithMany("Slots")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("ZachHairStudio.Shared.Features.Appointments.Appointment", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
