/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Appointments/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    serviceId?: number | string;
                    stylistId?: number | string;
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OpenSlotDto"][];
                        "application/json": components["schemas"]["OpenSlotDto"][];
                        "text/json": components["schemas"]["OpenSlotDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AppointmentCreateDto"];
                    "text/json": components["schemas"]["AppointmentCreateDto"];
                    "application/*+json": components["schemas"]["AppointmentCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AppointmentResponseDto"];
                        "application/json": components["schemas"]["AppointmentResponseDto"];
                        "text/json": components["schemas"]["AppointmentResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                    "text/json": components["schemas"]["LoginRequestDto"];
                    "application/*+json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponseDto"];
                        "application/json": components["schemas"]["LoginResponseDto"];
                        "text/json": components["schemas"]["LoginResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Availability/{stylistId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stylistId: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AvailabilityResponseDto"];
                        "application/json": components["schemas"]["AvailabilityResponseDto"];
                        "text/json": components["schemas"]["AvailabilityResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Availability/{stylistId}/working-hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stylistId: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkingHoursReplaceDto"];
                    "text/json": components["schemas"]["WorkingHoursReplaceDto"];
                    "application/*+json": components["schemas"]["WorkingHoursReplaceDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Availability/{stylistId}/time-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stylistId: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TimeOffCreateDto"];
                    "text/json": components["schemas"]["TimeOffCreateDto"];
                    "application/*+json": components["schemas"]["TimeOffCreateDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StylistTimeOff"];
                        "application/json": components["schemas"]["StylistTimeOff"];
                        "text/json": components["schemas"]["StylistTimeOff"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Availability/{stylistId}/time-off/{timeOffId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    stylistId: number | string;
                    timeOffId: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    status?: components["schemas"]["AppointmentStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AppointmentResponseDto"][];
                        "application/json": components["schemas"]["AppointmentResponseDto"][];
                        "text/json": components["schemas"]["AppointmentResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Schedule/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AppointmentResponseDto"];
                        "application/json": components["schemas"]["AppointmentResponseDto"];
                        "text/json": components["schemas"]["AppointmentResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Schedule/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AppointmentStatusUpdateDto"];
                    "text/json": components["schemas"]["AppointmentStatusUpdateDto"];
                    "application/*+json": components["schemas"]["AppointmentStatusUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AppointmentResponseDto"];
                        "application/json": components["schemas"]["AppointmentResponseDto"];
                        "text/json": components["schemas"]["AppointmentResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/Services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    includeInactive?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ServiceResponseDto"][];
                        "application/json": components["schemas"]["ServiceResponseDto"][];
                        "text/json": components["schemas"]["ServiceResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceCreateDto"];
                    "text/json": components["schemas"]["ServiceCreateDto"];
                    "application/*+json": components["schemas"]["ServiceCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ServiceResponseDto"];
                        "application/json": components["schemas"]["ServiceResponseDto"];
                        "text/json": components["schemas"]["ServiceResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Services/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetService"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Services/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceUpdateDto"];
                    "text/json": components["schemas"]["ServiceUpdateDto"];
                    "application/*+json": components["schemas"]["ServiceUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Services/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number | string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Image?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ServiceResponseDto"];
                        "application/json": components["schemas"]["ServiceResponseDto"];
                        "text/json": components["schemas"]["ServiceResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StaffUserCreateDto"];
                    "text/json": components["schemas"]["StaffUserCreateDto"];
                    "application/*+json": components["schemas"]["StaffUserCreateDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StaffUserResponseDto"];
                        "application/json": components["schemas"]["StaffUserResponseDto"];
                        "text/json": components["schemas"]["StaffUserResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Stylists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StylistResponseDto"][];
                        "application/json": components["schemas"]["StylistResponseDto"][];
                        "text/json": components["schemas"]["StylistResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppointmentCreateDto: {
            /** Format: int32 */
            serviceId?: number | string;
            /** Format: int32 */
            stylistId?: null | number | string;
            /** Format: date-time */
            startsAt?: string;
            firstName: string;
            lastName: string;
            email: string;
            phone?: null | string;
        };
        AppointmentResponseDto: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            serviceId?: number | string;
            serviceName?: string;
            /** Format: int32 */
            stylistId?: number | string;
            stylistName?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: int32 */
            durationMinutes?: number | string;
            /** Format: double */
            price?: number | string;
            status?: string;
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: null | string;
            /** Format: date-time */
            statusChangedAt?: null | string;
            statusChangedBy?: null | string;
        };
        AppointmentStatus: number;
        AppointmentStatusUpdateDto: {
            newStatus?: components["schemas"]["AppointmentStatus"];
        };
        AvailabilityResponseDto: {
            workingHours?: components["schemas"]["WorkingHoursSegmentDto"][];
            timeOff?: components["schemas"]["TimeOffResponseDto"][];
        };
        DayOfWeek: number;
        /** Format: binary */
        IFormFile: string;
        LoginRequestDto: {
            email?: string;
            password?: string;
        };
        LoginResponseDto: {
            token?: string;
            /** Format: date-time */
            expiresAt?: string;
            displayName?: string;
            role?: string;
        };
        OpenSlotDto: {
            /** Format: date-time */
            startsAt?: string;
            /** Format: int32 */
            stylistId?: null | number | string;
            stylistName?: null | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ServiceCreateDto: {
            slug: string;
            name: string;
            shortDescription: string;
            longDescription: string;
            category: string;
            /** Format: int32 */
            durationMinutes?: number | string;
            /** Format: double */
            price?: number | string;
            imageUrl?: null | string;
            /** Format: int32 */
            displayOrder?: number | string;
        };
        ServiceResponseDto: {
            /** Format: int32 */
            id?: number | string;
            slug?: string;
            name?: string;
            shortDescription?: string;
            longDescription?: string;
            category?: string;
            /** Format: int32 */
            durationMinutes?: number | string;
            /** Format: double */
            price?: number | string;
            imageUrl?: null | string;
            isActive?: null | boolean;
            /** Format: int32 */
            displayOrder?: number | string;
        };
        ServiceUpdateDto: {
            slug: string;
            name: string;
            shortDescription: string;
            longDescription: string;
            category: string;
            /** Format: int32 */
            durationMinutes?: number | string;
            /** Format: double */
            price?: number | string;
            imageUrl?: null | string;
            isActive?: boolean;
            /** Format: int32 */
            displayOrder?: number | string;
        };
        StaffUserCreateDto: {
            email?: string;
            displayName?: string;
            password?: string;
        };
        StaffUserResponseDto: {
            /** Format: int32 */
            id?: number | string;
            email?: string;
            displayName?: string;
            role?: string;
        };
        StylistResponseDto: {
            /** Format: int32 */
            id?: number | string;
            slug?: string;
            name?: string;
            /** Format: int32 */
            displayOrder?: number | string;
        };
        StylistTimeOff: {
            /** Format: int32 */
            id?: number | string;
            /** Format: int32 */
            stylistId?: number | string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            reason?: null | string;
        };
        TimeOffCreateDto: {
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            reason?: null | string;
        };
        TimeOffResponseDto: {
            /** Format: int32 */
            id?: number | string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            reason?: null | string;
        };
        WorkingHoursReplaceDto: {
            segments?: components["schemas"]["WorkingHoursSegmentDto"][];
        };
        WorkingHoursSegmentDto: {
            dayOfWeek?: components["schemas"]["DayOfWeek"];
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ServiceResponseDto"];
                    "application/json": components["schemas"]["ServiceResponseDto"];
                    "text/json": components["schemas"]["ServiceResponseDto"];
                };
            };
        };
    };
}
